- hosts: localhost
  connection: local
  collections:
    - vmware.alb
  tasks:
    - name: Create Pool object test
      avi_pool:
        state: present
        avi_credentials:
          username: "admin"
          password: "993HQSTPosL!"
          controller: "172.25.11.6"
          api_version: "22.1.3"
        name: test-app1-pool
        lb_algorithm: LB_ALGORITHM_LEAST_CONNECTIONS
        servers:
        - ip:
             addr: "192.168.12.15"
             type: 'V4'
