avi_config:
  pool:
    - name: "{{ app_name + '-pool' }}" 
      cloud_ref: "{{ '/api/cloud?name=' + cloud }}"
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      servers:
        - ip:
             addr: "{{ pool_server1 }}"
             type: 'V4'
        - ip:
             addr: "{{ pool_server2 }}"
             type: 'V4'
        - ip: 
             addr: "{{ pool_server3 }}"
             type: 'V4'
      tier1_lr: "{{ '/infra/tier-1s/' + tier1_lr }}"
  
  vsvip:
    - name: "{{ 'vsvip-' + app_name + '-' + cloud }}"
      cloud_ref: "{{ '/api/cloud?name=' + cloud }}"
      tenant: admin
      tenant_ref: /api/tenant/?name=admin
      vip:
      - auto_allocate_floating_ip: false
        auto_allocate_ip: false
        avi_allocated_fip: false
        avi_allocated_vip: false
        enabled: true
        ip_address:
          addr: "{{ app1_vip }}"
          type: V4
        vip_id: '1'
      tier1_lr: "{{ '/infra/tier-1s/' + tier1_lr }}"
      vrf_context_ref: "{{ '/api/vrfcontext/?name=' + tier1_lr}}"
 
  virtualservice:
    - name: "{{ 'vs-' + app_name }}"
      cloud_ref: "{{ '/api/cloud?name=' + cloud }}"
      services:
        - port: "{{ app_port }}"
          enable_ssl: false
      pool_ref: "{{ '/api/pool?name=' + app_name + '-pool'}}"
      vsvip_ref: "{{ '/api/vsvip/?name=vsvip-' + app_name + '-' + cloud }}"
      se_group_ref: "{{ '/api/serviceenginegroup/?name=' + se_group }}"
