# This is playbook for an application.
---
- hosts: localhost
  connection: local
  collections:
    - vmware.alb
  vars:
    app_name: app2
    app_port: 8080
 
  tasks:
    - name: Setting up Application
      debug: msg="{{ app_name }}"

    - name: Avi Application | Setup App2
      import_role:
        name: aviconfig
      vars:
        avi_config_file: "{{ site_dir }}/applications/{{app_name}}/config.yml"
        avi_creds_file: "{{ site_dir }}/vars/creds.yml"
