# This is playbook for a service engine group
---
- hosts: localhost
  connection: local
  collections:
    - vmware.alb
  vars:
    segroup_name: segroup2
    vcenter_name: vcenter
    vcenter_folder: test2
    cluster_ids: 
       - Cluster
    datastore_ids: 
       - vsanDatastore
       - nfsDatastore
  
  tasks:
    - name: Setting up Service Engine Group
      debug: msg="{{ segroup_name }}"

    - name: Avi Infrastructure | Setup Service Engine Group
      no_log: False
      import_role:
        name: aviconfig
      vars:
        avi_config_file: "{{ site_dir }}/segroups/{{segroup_name}}/config.yml"
        avi_creds_file: "{{ site_dir }}/vars/creds.yml"
